/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenlab10p2_gabrielgiron_12051024;

import java.awt.Color;
import java.util.Random;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Galex
 */
public class Menu extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarrosTree = new javax.swing.JTree();
        BarraJak = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BarraCarroMaligno = new javax.swing.JProgressBar();
        Iniciar = new javax.swing.JButton();
        Pausa = new javax.swing.JButton();
        AtkJaktxt = new javax.swing.JLabel();
        HpJaktxt = new javax.swing.JLabel();
        AtkErroltxt = new javax.swing.JLabel();
        HpErroltxt = new javax.swing.JLabel();
        BarraCiberErrol = new javax.swing.JProgressBar();
        Anunciador = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CarroName = new javax.swing.JTextField();
        CarroVida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CarroSpeed = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CarroTipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CarroAtk = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CarroDerrape = new javax.swing.JTextField();
        CrearCarro = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        CarroBox = new javax.swing.JComboBox<>();
        EliminarCarro = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Jak 3");

        CrearJTree();
        UpdateJTree();
        jScrollPane1.setViewportView(CarrosTree);

        jLabel2.setText("Jak");

        jLabel3.setText("Ciber Errol");

        Iniciar.setText("Iniciar Partida");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        Pausa.setText("Pausar/Reaunadar Partida");
        Pausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PausaActionPerformed(evt);
            }
        });

        AtkJaktxt.setText("Ataque Jak: ");

        HpJaktxt.setText("Vida Jak: ");

        AtkErroltxt.setText("Ataque Ciber Errol: ");

        HpErroltxt.setText("Vida Ciber Errol: ");

        Anunciador.setText("----------------------------------------------------------------------------------------------");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Anunciador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BarraJak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BarraCarroMaligno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Pausa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(BarraCiberErrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AtkJaktxt, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(HpJaktxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AtkErroltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HpErroltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BarraJak, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BarraCarroMaligno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BarraCiberErrol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Iniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pausa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AtkJaktxt)
                    .addComponent(AtkErroltxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HpJaktxt)
                    .addComponent(HpErroltxt))
                .addGap(18, 18, 18)
                .addComponent(Anunciador, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Juego", jPanel1);

        jLabel4.setText("Nombre");

        jLabel5.setText("Vida");

        jLabel6.setText("Velocidad");

        CarroTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Belico", "Salto", "Ataque" }));

        jLabel7.setText("Tipo");

        jLabel8.setText("Ataque");

        jLabel9.setText("Derrape");

        CrearCarro.setText("Crear");
        CrearCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCarroActionPerformed(evt);
            }
        });

        jLabel10.setText("Eliminar Carro");

        CarroBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        setComboBox();
        CarroBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarroBoxActionPerformed(evt);
            }
        });

        EliminarCarro.setText("Eliminar");
        EliminarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CrearCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(CarroAtk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                        .addComponent(CarroName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CarroSpeed, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CarroVida)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CarroTipo, 0, 170, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CarroDerrape))))
                        .addGap(58, 58, 58))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EliminarCarro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CarroBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarroName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CarroVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarroSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CarroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarroAtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CarroDerrape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(CrearCarro)
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarroBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EliminarCarro)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Carros", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 319, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCarroActionPerformed
        // TODO add your handling code here:
        String Name = CarroName.getText();
        double Atk = Double.parseDouble(CarroAtk.getText());
        int Speed = Integer.parseInt(CarroSpeed.getText());
        int Derrape = Integer.parseInt(CarroDerrape.getText());
        double Hp = Double.parseDouble(CarroVida.getText());
        AC.cargarArchivo();
        if(CarroTipo.getSelectedItem().equals("Normal"))
        {
           Carros C = new Carros(Name,Speed,Derrape,Atk,Hp);
           AC.getListaCarros().add(C);
        }
        else if(CarroTipo.getSelectedItem().equals("Belico"))
        {
            Belico B = new Belico(Name,Speed,Derrape,Atk,Hp);
            AC.getListaCarros().add(B);
        }
        else if(CarroTipo.getSelectedItem().equals("Salto"))
        {
            Carros C = new Carros(Name,Speed,Derrape,Atk,Hp);
            AC.getListaCarros().add(C);
        }
        else if(CarroTipo.getSelectedItem().equals("Ataque"))
        {
            Ataque A = new Ataque(Name,Speed,Derrape,Atk,Hp);
            AC.getListaCarros().add(A);
        }
        AC.escribirArchivo();
        UpdateJTree();
        JOptionPane.showMessageDialog(this, "Carro Creado Exitosamente");
    }//GEN-LAST:event_CrearCarroActionPerformed

    private void CarroBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarroBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarroBoxActionPerformed

    private void EliminarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCarroActionPerformed
        // TODO add your handling code here:
        AC.cargarArchivo();
        CarroBox.remove(CarroBox.getSelectedIndex());
        System.out.println(AC.getListaCarros().size());
        System.out.println(CarroBox.getSelectedIndex());
        AC.getListaCarros().remove(CarroBox.getSelectedIndex());
        AC.escribirArchivo();
        UpdateJTree();
        setComboBox();
        JOptionPane.showMessageDialog(this, "Carro Borrado Exitosamente");
    }//GEN-LAST:event_EliminarCarroActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        // TODO add your handling code here:
        CrearCarroMaligno();
        System.out.println(CarroMalignoVida);
        AC.cargarArchivo();
        for(int i = 0; i < AC.getListaCarros().size(); i++)
        {
            if(CarrosTree.getSelectionPath().toString().equals("[Carros, "+AC.getListaCarros().get(i).getNombre()+"]"))
            {
                AtaqueJak = (int) AC.getListaCarros().get(i).getAtaque();
                VidaJak = (int) AC.getListaCarros().get(i).getVida();
                CiberErrolAtk = CarroMalignoAtk;
                BarraJak.setMaximum((int) AC.getListaCarros().get(i).getVida());
                BarraJak.setValue((int) AC.getListaCarros().get(i).getVida());
                
                BarraJak.setForeground(Color.green);
                
                BarraCarroMaligno.setMaximum(CarroMalignoVida);
                BarraCiberErrol.setMaximum(CiberErrolVida);
                
                BarraCarroMaligno.setValue(CarroMalignoVida);
                BarraCiberErrol.setValue(CiberErrolVida);
                
                BarraCiberErrol.setForeground(Color.red);
                BarraCarroMaligno.setForeground(Color.red);
                
                AtkJaktxt.setText("Ataque Jak: "+AC.getListaCarros().get(i).getAtaque());
                HpJaktxt.setText("Vida Jak: "+AC.getListaCarros().get(i));
                AtkErroltxt.setText(CarroMaligno);
                run();
                break;
            }
        }
        
    }//GEN-LAST:event_IniciarActionPerformed

    private void PausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PausaActionPerformed
        // TODO add your handling code here:
        if(Pause == false)
            Pause = true;
        else if(Pause == true)
            Pause = false;
    }//GEN-LAST:event_PausaActionPerformed
    
    private void CrearCarroMaligno()
    {
        CarroMalignoAtk = 3+R.nextInt(5);
        CarroMalignoVida = 1+R.nextInt(5);
        CarroMaligno = "Carro Maligno";
        
        switch(CarroMalignoAtk)
        {
            case 3 ->             {
                CarroMalignoAtk = 300;
            }
            case 4 ->             {
                CarroMalignoAtk = 400;
            }
            case 5 ->             {
                CarroMalignoAtk = 500;
            }
            case 6 ->             {
                CarroMalignoAtk = 600;
            }
            case 7 ->             {
                CarroMalignoAtk = 700;
            }
        }
        
        switch(CarroMalignoVida)
        {
            case 1 ->             {
                CarroMalignoVida = 1000;
            }
            case 2 ->             {
                CarroMalignoVida = 2000;
            }
            case 3 ->             {
                CarroMalignoVida = 3000;
            }
            case 4 ->             {
                CarroMalignoVida = 4000;
            }
            case 5 ->             {
                CarroMalignoVida = 5000;
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    private void CrearJTree()
    {
        DefaultMutableTreeNode tables = new DefaultMutableTreeNode("Carros");
        Arbol = new JTree(tables);
        CarrosTree = Arbol;
    }
    private void UpdateJTree()
    {
        DefaultTreeModel Modelo = (DefaultTreeModel) CarrosTree.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) Modelo.getRoot();
        AC.cargarArchivo();
        if(raiz.getChildCount() == 0)
        {
            for(int i = 0; i < AC.getListaCarros().size(); i++)
            {
                DefaultMutableTreeNode Componente = new DefaultMutableTreeNode(AC.getListaCarros().get(i).getNombre());
                raiz.add(Componente);
            }
        }
        else
        {
            int cont = 0;
            for(int i = 0; i < AC.getListaCarros().size(); i++)
            {
                if(raiz.getChildAt(i).toString().equals(AC.getListaCarros().get(i).getNombre()) && cont != raiz.getChildCount() - 1)
                {
                    cont++;
                }
                else
                {
                    DefaultMutableTreeNode Componente = new DefaultMutableTreeNode(AC.getListaCarros().get(i+1).getNombre());
                    raiz.add(Componente);
                    break;
                }
            }
        }
        Modelo.reload();
    }
    private void setComboBox()
    {
        AC.cargarArchivo();
        DefaultComboBoxModel Model = new DefaultComboBoxModel();
        JComboBox combo = new JComboBox(Model);
        if(AC.getListaCarros().size()== 0)
        {
            CarroBox = combo;
        }
        else
        {
            for(int i = 0; i < AC.getListaCarros().size(); i++)
            {
                Model.addElement(AC.getListaCarros().get(i));
            }
            CarroBox = combo;
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anunciador;
    private javax.swing.JLabel AtkErroltxt;
    private javax.swing.JLabel AtkJaktxt;
    private javax.swing.JProgressBar BarraCarroMaligno;
    private javax.swing.JProgressBar BarraCiberErrol;
    private javax.swing.JProgressBar BarraJak;
    private javax.swing.JTextField CarroAtk;
    private javax.swing.JComboBox<String> CarroBox;
    private javax.swing.JTextField CarroDerrape;
    private javax.swing.JTextField CarroName;
    private javax.swing.JTextField CarroSpeed;
    private javax.swing.JComboBox<String> CarroTipo;
    private javax.swing.JTextField CarroVida;
    private javax.swing.JTree CarrosTree;
    private javax.swing.JButton CrearCarro;
    private javax.swing.JButton EliminarCarro;
    private javax.swing.JLabel HpErroltxt;
    private javax.swing.JLabel HpJaktxt;
    private javax.swing.JButton Iniciar;
    private javax.swing.JButton Pausa;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    private JTree Arbol;
    private AdminCarros AC = new AdminCarros("./Carros");
    Random R = new Random();
    private boolean Pause = false;
    private String CarroMaligno;
    private int CarroMalignoAtk;
    private int CarroMalignoVida;
    private int CiberErrolVida = 30000;
    private int CiberErrolAtk;
    private int AtaqueJak;
    private int VidaJak;
    int count;
    Thread Hilo = new Thread();

    @Override
    public void run() {
        while(true)
        {
            System.out.println(CarroMalignoAtk);
            try
            {
                while(Pause == false)
                {
                    while(BarraJak.getValue() > 0 && BarraCiberErrol.getValue() > 0)
                    {
                        if(BarraCarroMaligno.getValue() > 0)
                        {
                            if(count == 2)
                            {
                                BarraCarroMaligno.setValue(BarraCarroMaligno.getValue() - AtaqueJak);
                                count = 0;
                            }
                            BarraJak.setValue(BarraJak.getValue() - CarroMalignoAtk);
                            count++;
                            Thread.sleep(500);
                        }
                        else
                        {
                            if(count == 2)
                            {
                                BarraCiberErrol.setValue(BarraCiberErrol.getValue() - AtaqueJak);
                                count = 0;
                            }
                            BarraJak.setValue(BarraJak.getValue() - CarroMalignoAtk);
                            count++;
                            Thread.sleep(500);
                        }
                    }
                }
                if(BarraJak.getValue() < 0)
                {
                    JOptionPane.showMessageDialog(this, "Perdiste :(");
                }
                else if(BarraCiberErrol.getValue() < 0)
                {
                    
                }
            }
            catch(Exception E)
            {
                E.printStackTrace();
            }
        }
    }
    

}
